filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/auth.log
  fields:
    log_type: ssh_auth
  fields_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "security-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"

setup.ilm.enabled: false
setup.template.name: "security-logs"
setup.template.pattern: "security-logs-*"
